export const copy = {
  brand: {
    name: "Retain",
    descriptor: "VIDEOANALYS",
  },
  meta: {
    title: "Retain — AI-coach för kortformatsvideo",
    description: "Tidsstämplad feedback på din hook, tempo, tydlighet och retentionspotential.",
    ogTitle: "Retain — Fixa din video innan du postar den.",
    ogDescription: "Tidsstämplad AI-feedback för starkare kortformatsvideor.",
  },
  actions: {
    upload: "Ladda upp",
    analyse: "Analysera",
    copy: "Kopiera",
    copied: "Kopierad",
    reset: "Analysera en ny video",
    tryAgain: "Försök igen",
    loadDemo: "Visa exempelrapport",
  },
  scoreLabels: {
    "Needs work": "Behöver arbete",
    Promising: "Lovande",
    Strong: "Stark",
    Excellent: "Utmärkt",
  },
  categoryScores: {
    hook: "Hook",
    pacing: "Tempo",
    clarity: "Tydlighet",
    visualEngagement: "Visuellt intryck",
    audioDelivery: "Ljud",
    payoff: "Avslutning",
    audienceFit: "Målgrupp",
  },
  severity: {
    low: "låg",
    medium: "medel",
    high: "hög",
  },
  goals: {
    views: "Visningar",
    engagement: "Engagemang",
    followers: "Följare",
    conversions: "Konverteringar",
  },
  disclaimer: "Detta är kreativ vägledning för redigering och kan inte garantera resultat.",
  styleguide: {
    title: "Stilguide",
    intro: "Designtokens, typografiskala och byggstenar för det nya gränssnittet — granskas här innan de används på riktiga sidor.",
    sections: {
      palette: { eyebrow: "01", title: "Färgpalett" },
      typography: { eyebrow: "02", title: "Typografi" },
      spacing: { eyebrow: "03", title: "Rytm & avstånd" },
      buttons: { eyebrow: "04", title: "Knappar" },
      form: { eyebrow: "05", title: "Formulärfält" },
      score: { eyebrow: "06", title: "Poängvisning" },
      motion: { eyebrow: "07", title: "Rörelse" },
    },
    paletteLabels: {
      background: "Bakgrund",
      surface: "Yta (upphöjd)",
      border: "Kantlinje",
      text: "Text, primär",
      textMuted: "Text, sekundär",
      accent: "Accent (enda färgen)",
    },
    typographyLabels: {
      display: "Rubrik — Newsreader",
      body: "Brödtext — Geist, max 68ch",
      tabular: "Tabellsiffror i poäng",
    },
    formLabel: "Nisch eller mål",
    formPlaceholder: "t.ex. produkttips för hudvård",
    scoreSample: [
      { label: "Hook", value: 82 },
      { label: "Tempo", value: 64 },
      { label: "Tydlighet", value: 91 },
    ],
    motionCaption: "Tona in + förflyttning, 240ms, utlöses en gång vid synlighet. Respekterar reducerad rörelse.",
  },
} as const;
